import { PORTFOLIO_LINKS } from "./links";
import {
  BOOKS_DESK_X,
  BOOKS_MAX_H,
  CAMERA_HANG_X,
  CAMERA_HANG_Y,
  CLOCK_SHELF_X,
  DESK_SURFACE_Y,
  LAMP_HEIGHT,
  LAMP_ORIGIN_X,
  MONITOR_LEFT_X,
  MONITOR_TOTAL_H,
  MONITOR_TOTAL_W,
  MUG_DESK_X,
  MUG_HEIGHT,
  PLANT_HEIGHT,
  PLANT_SHELF_CONTACT_Y,
  PLANT_SHELF_X,
  PLANT_WIDTH,
  SHELF_LEFT_Y,
  SPEAKER_HANG_X,
  SPEAKER_HANG_Y,
} from "./deskLayout";

export const WORKSPACE_OBJECTS = [
  {
    id: "books",
    labelKey: "books",
    ariaLabelKey: "books",
    href: PORTFOLIO_LINKS.mfaThesis,
    transform: `translate(${BOOKS_DESK_X}, ${DESK_SURFACE_Y - BOOKS_MAX_H})`,
    labelOffset: { x: 2, y: -6 },
  },
  {
    id: "plant",
    action: "plant",
    ariaLabelKey: "plantAria",
    hideLabel: true,
    transform: `translate(${PLANT_SHELF_X}, ${SHELF_LEFT_Y - PLANT_SHELF_CONTACT_Y})`,
    tooltipOffset: { x: -8, y: 28 },
    tooltipAlign: "end",
    hitBounds: { x: -4, y: -6, width: PLANT_WIDTH + 12, height: PLANT_HEIGHT },
  },
  {
    id: "clock",
    labelKey: "clock",
    ariaLabelKey: "clockAria",
    hideLabel: true,
    transform: `translate(${CLOCK_SHELF_X}, ${SHELF_LEFT_Y - 78})`,
    tooltipOffset: { x: 84, y: 12 },
  },
  {
    id: "speaker",
    action: "music",
    labelKey: "musicPlay",
    ariaLabelKey: "musicAria",
    hideLabel: false,
    transform: `translate(${SPEAKER_HANG_X}, ${SPEAKER_HANG_Y})`,
    labelOffset: { x: 2, y: -6 },
  },
  {
    id: "camera",
    labelKey: "camera",
    href: PORTFOLIO_LINKS.rednote,
    transform: `translate(${CAMERA_HANG_X}, ${CAMERA_HANG_Y})`,
    labelOffset: { x: 4, y: -6 },
  },
  {
    id: "lamp",
    labelKey: "lamp",
    action: "lamp",
    transform: `translate(${LAMP_ORIGIN_X}, ${DESK_SURFACE_Y - LAMP_HEIGHT})`,
    labelOffset: { x: 8, y: -10 },
  },
  {
    id: "monitor",
    labelKey: "monitor",
    href: PORTFOLIO_LINKS.portfolio,
    transform: `translate(${MONITOR_LEFT_X}, ${DESK_SURFACE_Y - MONITOR_TOTAL_H})`,
    labelOffset: { x: MONITOR_TOTAL_W / 2 - 20, y: -10 },
  },
  {
    id: "mug",
    action: "mug",
    ariaLabelKey: "mugAria",
    hideLabel: true,
    transform: `translate(${MUG_DESK_X}, ${DESK_SURFACE_Y - MUG_HEIGHT})`,
    tooltipOffset: { x: 66, y: -16 },
  },
];
